### PR TITLE
vertically center hero video and text

### PR DESCRIPTION
**Pull request by lynlevenick**
this is most apparent when i open dev tools, but this should focus the hero video's gameplay more on the action - right now it shows the top, which can look semi-awkward

in addition, this makes the BEYOND MELEE/download text visible when at an especially wide but thin viewport

### CODE REVIEW

**Comment by cynthetic-boop** [comment]
I had a lot of problems getting the hero video to work with the image on top.  If there is a way to make it work reliably and responsively that would be great.

**Comment by lynlevenick** [comment]
dealing with the image on top responsively kinda depends on what you want out of the design? this is a slight clean up of what i think you were going for, but if you're willing to tweak the way the hero space works then there's some more options - I think this could be set up really nicely & responsively with [CSS grid](https://caniuse.com/css-grid) if you're willing to not have it work perfectly in older browsers, maybe i'll chat more on discord about it?

**Review by cynthetic-boop — COMMENTED** [review]
i wish i could preview this. does it still work basically the same as what we want?

**Review by cynthetic-boop — APPROVED** [review]
yeah

**Pull request merged**
